refactoring of example folder
provectus/swiss-army-kube pull request #107
Opened 2020-11-10 11:22 UTC by RustamGimadiev

- added inner examples structure
- all examples are simple Terraform code, not modules

2020-11-10 12:01 UTC, akastav commented on examples/common/providers.tf
> +  region  = "us-west-2"
Could you please add notation about this params to readme

2020-11-10 13:20 UTC, Evanto requested changes

2020-11-10 13:20 UTC, Evanto commented on QUICKSTART.md
> +The `swiss-army-kube/examples` directory are a boilerplates for your projects, use them as a template. You can rename it to your project name for convenience. Make as many projects as you need by clo
The `swiss-army-kube/examples` directory contains project examples that you can use as boilerplates to start your new projects. Pick one, rename it to your project name for convenience, and modify the directory as required. This way you can create as many projects as you need really fast.

2020-11-10 13:20 UTC, Evanto commented on QUICKSTART.md
> +NOTE: To change developers permissions on Kubernetes cluster manipulate `cluster_roles` variable in the `main.tf` file.
NOTE: To change developers' permissions on the Kubernetes cluster edit the `cluster_roles` variable in the `main.tf` file.

2020-11-10 13:20 UTC, Evanto commented on README.md
> +SAK provides an examples directories that you can use as an easily modifiable template to set up your cluster deployment configuration in minutes. All you need is to edit a couple of files to include
SAK provides example directories that you can use as easily modifiable templates to set up your cluster deployment configuration in minutes. All you need is to edit a couple of files to include modules and set variables. This way you can quickly configure and provision multiple dedicated EKS Kubernetes clusters with different configurations of modules, variables, networks, and Kubernetes versions.

2020-11-10 13:20 UTC, Evanto commented on README.md
>     + Configure modules
maybe modules and variables?

2020-11-10 15:50 UTC, akastav approved these changes

2020-11-11 08:42 UTC, Evanto submitted a review, later dismissed

2020-11-11 09:12 UTC, akastav approved these changes

2020-11-11 09:14 UTC, merged